services:
  nginx:
    build: .
    image: mabdelgawad94/nginx:latest      # keep your tag
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # certificates (read-write so certbot can renew)
      - ./certs:/etc/nginx/certs:rw
      # mount the whole conf directory so default.conf **and** snippets are visible
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      # Mount the shared media volume from the portfolio app, read-only
      - portfolio_media_data:/var/www/media:ro
    networks:
      - nginx_network
    restart: always

volumes:
  portfolio_media_data:
    external: true

networks:
  nginx_network:
    name: nginx_network
