services:
  nginx:
    build: .
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
    restart: always