services:
  nginx:
    build: .
    container_name: nginx
    image: mabdelgawad94/nginx:latest
    pull_policy: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nginx_network
    restart: always

networks:
  nginx_network:
    name: nginx_network
