version: '3.8'

services:
  nginx:
    build: .
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/snippets:/etc/nginx/snippets
      - ./certs:/etc/nginx/certs
    networks:
      - app-network
    restart: unless-stopped

  # Example app container (add more as needed)
  myreads-frontend:
    image: myreads-frontend:latest
    container_name: myreads-frontend
    networks:
      - app-network
    restart: unless-stopped

  myreads-backend:
    image: myreads-backend:latest
    container_name: myreads-backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
